# Generated by Django 3.1.2 on 2020-11-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0002_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.FileField(upload_to='bookEx/static/uploads'),
        ),
    ]
