# Generated by Django 3.1.3 on 2020-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookMng', '0014_auto_20201127_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='taken_down',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
