# Generated by Django 3.1 on 2020-12-02 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookMng', '0015_book_taken_down'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('web', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('picture', models.FileField(upload_to='bookEx/static/uploads')),
                ('pic_path', models.CharField(blank=True, editable=False, max_length=300)),
                ('taken_down', models.BooleanField(default=False, null=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
